version: '3.7'
services:
  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: whoami8.accesstechnology.co.uk
      caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy:
    external: true
