#version: '3.7'
services:

  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - caddy
    labels:
      caddy: ${APP_NAME}.accesstechnology.co.uk
      caddy.root: "* $PWD/public"
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.php_fastcgi.root: /var/www/public
      caddy.encode: gzip
      caddy.file_server:
      # remove the following line when you have verified your setup
      # Otherwise you risk being rate limited by let's encrypt
      caddy.tls.ca: https://acme-staging-v02.api.letsencrypt.org/directory
#Docker Networks
networks:
  caddy:
    external: true
